language: ruby

script:
  - cd subscription-artwork
  - mkdir feeds
  - cd feeds
  - wget `ruby ../getFeeds.rb ../example_opml.xml`
  - cd ..
  - mkdir pics
  - cd pics
  - ruby ../getArtwork.rb ../feeds/* | sort | uniq | xargs wget
